name: 测试
on:
  workflow_dispatch:
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json
      
      - name: '【测试】'
        run: |  
          node Task/sqxs0.js
 








