name: 书旗小说3
on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '0 3,5 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json
      
      - name: '【书旗小说3-视频】'
        run: |  
          node Task/sqxs3_video.js
          
      - name: '【书旗小说3-阅读】'
        run: |  
          node Task/sqxs3_read.js








