name: 书旗小说2
on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '0 2,4 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    if: github.event.repository.owner.id == github.event.sender.id
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json

         
      - name: '【书旗小说2-视频】'
        run: |  
          node Task/sqxs2_video.js
        env:
         SQ_COOKIES: ${{secrets.SQ_COOKIES}};
          
      - name: '【书旗小说2-阅读】'
        run: |  
          node Task/sqxs2_read.js
        env:
         SQ_COOKIES: ${{secrets.SQ_COOKIES}};








